grpc:
  port: 6060
  timeout: 5s

userMicroservice:
  host: authentication-service
  port: 5050


reservationMicroservice:
  host: reservation-service
  port: 9090

qrMicroservice:
  host: qrcode-service
  port: 7070